# Configuration file for ReadTheDocs
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-20.04
  apt_packages:
    - graphviz
  tools:
    python: "3.9"

python:
  install:
    - requirements: requirements/documentation.txt

sphinx:
  builder: html
  configuration: docs/source/conf.py
