# Generated by Django 3.2.9 on 2021-11-26 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calingen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='event_provider',
            new_name='_event_provider',
        ),
    ]
