# Generated by Django 3.2.9 on 2021-11-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calingen', '0002_rename_event_provider_profile__event_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('ANNUAL_ANNIVERSARY', 'Annual Anniversary'), ('HOLIDAY', 'Holiday')], default='ANNUAL_ANNIVERSARY', help_text='The type of this event.', max_length=18, verbose_name='Event Type'),
        ),
    ]
