name: CI

on:
  push:
    branches: [dev-setup]
  pull_request:
    branches: [dev-setup]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Run black
        run: make util/black
      - name: Run mypy
        run: make util/mypy
      - name: Run flake8
        run: make util/flake8
      - name: Run bandit
        run: make util/bandit


  testing:
    needs: linting
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup OS ${{ matrix.platform }} - Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions coveralls coverage[toml]
      - name: Run tests with tox
        run: tox
        env:
          PLATFORM: ${{ matrix.platform }}
      - name: Prepare coverage result
        run: |
          coverage combine --append
          coveralls
